# Generated by Django 4.1.13 on 2024-05-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_page_section_delete_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='geeks_field',
            new_name='link',
        ),
        migrations.AddField(
            model_name='page',
            name='category',
            field=models.CharField(default='upt', max_length=50),
            preserve_default=False,
        ),
    ]
