# Generated by Django 4.1.13 on 2024-05-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_geeks_field_page_link_page_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='link',
            field=models.CharField(max_length=200),
        ),
    ]
