# Generated by Django 4.1.13 on 2024-05-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_page_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['position']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['position']},
        ),
        migrations.AddField(
            model_name='page',
            name='position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='position',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
